[workspace]
resolver = "3"
members = ["cli", "library"]

[patch.crates-io]
credence-lib = { path = "library" }

[profile.dev]
debug = false

[profile.release]
# Especially important for wasm!
strip = "debuginfo"
lto = "thin"        # true is *very* slow to build!
